"""empty message

Revision ID: b2bb9924f269
Revises: 63cd8d0d5438
Create Date: 2018-11-26 21:02:40.420297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bb9924f269'
down_revision = '63cd8d0d5438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('username', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_column('employee', 'username')
    # ### end Alembic commands ###
